sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: npm
  email: calvinclaus@me.com
  api_key:
    secure: WvsIh9HhW+S6EJAmsixfA+qMzWJdhjiKFYFEhXK6jpfoHY9MAxaY0/ge/dvlCnJVs8FmJmrZbPqraheatqtVvOHwOaMUbR+Zm0csjUfCCLpcjafNqobs0q90R6eIdm9Ymbon/pAS5UfjIYNho82UmdJb0aC6yIjf6FD4oqCrwfhxJwlB1/8gojaccD87x3Jn8aEulxpPFQk0ai1gwPT/mU+uD35TAXtMub/nTpVXokakg88ez6sLGAN6QeQ+5WIT3qmjj9RrED2DIq7AgP3m1rCByBUrmic2x3PjKI1B/bJnb9rU7cVIv4twQ/8evD5Ki192kX0BUVBzdEcVTaLoFjI5mx27geu1hkc4cLEbzEkenap4FXagz5qrRbocTnZ+95LFjQotHQLU3GNuHSCOhrtGVob/+pnv90kS7s9vO6gimPNUTkffCVhwDu8RK1jttJN2tpAT9nUWpwAO+TRA4YOkDwNmwegFJZybZsC+2Q9SNr1DcQyI6HRIqlE0QVik5Zp+JZsbT3NCWafYIDNmwkblVa/Xp+mXKO5rfNFGF+F8pcs4aoT2BWjQD7YEKW24EAE1mk/cad8q7HbY+7ZnrkGUGUHHw3haLpqd7rPCsIp/aRp7l4ovbsZnEcj8s0EkqmTfizIzRItBTNFqFWlimLL4dPvoPwtQ5t4L4kK39wE=
  on:
    repo: calvinclaus/facebook-opening-hours-to-table
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
script:
- npm run test:single
- npm run check-coverage
- npm run build
after_success:
- npm run report-coverage
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
